### ISSUE TITLE
Edit individual

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#383]
If I try to edit one of my individuals and I do not change anything then I press save
I get the following error:

```

Traceback (most recent call last):
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
herdbook-main |     return self.wsgi_app(environ, start_response)
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
herdbook-main |     response = self.handle_exception(e)
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
herdbook-main |     reraise(exc_type, exc_value, tb)
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
herdbook-main |     raise value
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
herdbook-main |     response = self.full_dispatch_request()
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
herdbook-main |     rv = self.handle_user_exception(e)
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
herdbook-main |     reraise(exc_type, exc_value, tb)
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
herdbook-main |     raise value
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
herdbook-main |     rv = self.dispatch_request()
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
herdbook-main |     return self.view_functions[rule.endpoint](**req.view_args)
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
herdbook-main |     return func(*args, **kwargs)
herdbook-main |   File "/code/./herdbook.py", line 575, in edit_individual
herdbook-main |     retval = da.update_individual(form, session.get("user_id", None))
herdbook-main |   File "/code/./utils/data_access.py", line 979, in update_individual
herdbook-main |     individual = form_to_individual(form, user)
herdbook-main |   File "/code/./utils/data_access.py", line 790, in form_to_individual
herdbook-main |     f"{form[admin_field]}" != f"{getattr(individual, admin_field)}"
herdbook-main | AttributeError: 'Individual' object has no attribute 'birth_date'

```

**Comment by airenzp** [comment]
Is this solved? So it seems to me when testing

**Comment by jhagberg** [comment]
Yes
