### ISSUE TITLE
Add breeding and birth event generates permission error

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#386]
Adding both a breeding and birth event I get permission error and error in front end

```
herdbook-main | [pid: 21|app: 0|req: 154/154] 127.0.0.1 () {60 vars in 1046 bytes} [Thu Sep  2 13:37:22 2021] POST /api/individual => generated 0 bytes in 12 msecs (HTTP/1.0 500) 0 headers in 0 bytes (0 switches on core 3)
herdbook-main | Traceback (most recent call last):
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
herdbook-main |     return self.wsgi_app(environ, start_response)
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
herdbook-main |     response = self.handle_exception(e)
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
herdbook-main |     reraise(exc_type, exc_value, tb)
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
herdbook-main |     raise value
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
herdbook-main |     response = self.full_dispatch_request()
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
herdbook-main |     rv = self.handle_user_exception(e)
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
herdbook-main |     reraise(exc_type, exc_value, tb)
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
herdbook-main |     raise value
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
herdbook-main |     rv = self.dispatch_request()
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
herdbook-main |     return self.view_functions[rule.endpoint](**req.view_args)
herdbook-main |   File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
herdbook-main |     return func(*args, **kwargs)
herdbook-main |   File "/code/./herdbook.py", line 577, in edit_individual
herdbook-main |     retval = da.add_individual(form, session.get("user_id", None))
herdbook-main |   File "/code/./utils/data_access.py", line 890, in add_individual
herdbook-main |     individual = form_to_individual(form, user)
herdbook-main |   File "/code/./utils/data_access.py", line 747, in form_to_individual
herdbook-main |     raise PermissionError
herdbook-main | PermissionError
```

**Comment by jhagberg** [comment]
Should be fixed by pr #391
