### ISSUE TITLE
Missing key error in test mating

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/theherdbook#416]
This should  not happen perhaps something fishy with my database but we should perhaps improve and catch this?

```
INFO:herdbook:Testbreed calculation input {'genebankId': 1, 'male': 'G786-1323', 'female': 'G1274-1811'}
herdbook-main              | Traceback (most recent call last):
herdbook-main              |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
herdbook-main              |     return self.wsgi_app(environ, start_response)
herdbook-main              |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
herdbook-main              |     response = self.handle_exception(e)
herdbook-main              |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
herdbook-main              |     reraise(exc_type, exc_value, tb)
herdbook-main              |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
herdbook-main              |     raise value
herdbook-main              |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
herdbook-main              |     response = self.full_dispatch_request()
herdbook-main              |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
herdbook-main              |     rv = self.handle_user_exception(e)
herdbook-main              |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
herdbook-main              |     reraise(exc_type, exc_value, tb)
herdbook-main              |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
herdbook-main              |     raise value
herdbook-main              |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
herdbook-main              |     rv = self.dispatch_request()
herdbook-main              |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
herdbook-main              |     return self.view_functions[rule.endpoint](**req.view_args)
herdbook-main              |   File "/code/./herdbook.py", line 692, in testbreed
herdbook-main              |     offspring_coi = kinship_matrix[payload["male"]][payload["female"]]
herdbook-main              | KeyError: 'G786-1323'

```

**Comment by jhagberg** [comment]
No this is a new bug in the backend since we no long only show active rabbits line 690 in herdbook just assume we send two active parents. So we need to improve and check if male and female are from active population then get value from kinship matrix otherwise wee need to calculate.
